name: edu_app
description: "KU MAD CW2 -Educational application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.1
  flutter_svg: ^2.0.16
  jiffy: ^6.3.1
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  flutter_widget_from_html: ^0.15.3
  image_picker: ^0.8.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  assets:
  - .env
  - assets/images/welcome.png
  - assets/images/avatar.jpg
  - assets/images/book-1.jpg
  - assets/images/book-2.jpg
  - assets/images/book-3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
